In [1]:
from models.dense import DenseModel
import numpy as np

Using TensorFlow backend.


In [2]:
model_obj = DenseModel('Dense_1')
model = model_obj.model

model found at ./Dense_1.h5


In [3]:
weights = []
for layer in model.layers:
    weights.append(layer.get_weights())

In [4]:
l1_weights = weights[0][0].T
for i in range(len(l1_weights)):
    neuron_1_w = l1_weights[i]
    sorted_weights = sorted(neuron_1_w)
    index = np.where(neuron_1_w>=sorted_weights[-3])
    print(index, neuron_1_w[index])

(array([ 9, 19, 24]),) [2.3070989 2.1874132 1.9661651]
(array([13, 15, 21]),) [3.0505643 3.8516297 1.6936251]
(array([12, 16, 19]),) [2.9560826 1.6581903 2.4252746]
(array([ 0,  7, 22]),) [1.1299574 1.9628311 0.9498364]
(array([ 1,  7, 18]),) [2.3425655 1.3812815 1.0763162]
(array([17, 19, 21]),) [0.7734723 1.7425798 0.764288 ]
(array([ 0, 20, 25]),) [2.8164465 2.114167  2.172567 ]
(array([ 4,  7, 19]),) [2.6827035 2.7110486 5.880094 ]
(array([13, 21, 26]),) [2.3616707 4.1106925 1.7211565]


In [5]:
l1_weights[0]

array([-9.053276  , -3.3004231 ,  0.84520483,  0.37401932, -3.1205504 ,
        0.10361762, -2.778006  , -1.4184844 , -0.13806844,  2.3070989 ,
       -7.520306  , -0.58609635,  1.7751559 , -2.5935845 ,  0.25114328,
       -0.46329007, -0.19498797, -0.23960085,  0.8101602 ,  2.1874132 ,
        0.30604988, -0.6257976 ,  0.5407814 ,  0.29297498,  1.9661651 ,
       -2.5231519 , -0.8536153 ], dtype=float32)

In [6]:
len(weights)

1

In [7]:
len(weights[0][0])

27

In [8]:
len(l1_weights.T)

27