In [1]:
from models.dense import DenseModel
import numpy as np

Using TensorFlow backend.


In [2]:
model_obj = DenseModel('Dense_1')
model = model_obj.model

model found at ./Dense_1.h5


In [3]:
weights = []
for layer in model.layers:
    weights.append(layer.get_weights())

In [4]:
l1_weights = weights[0][0].T
for i in range(len(l1_weights)):
    neuron_1_w = l1_weights[i]
    sorted_weights = sorted(neuron_1_w)
    index = np.where(neuron_1_w>=sorted_weights[-3])
    print(index, neuron_1_w[index])

(array([ 3, 10, 18]),) [1.2395992 2.1489027 1.867734 ]
(array([ 1,  9, 19]),) [2.1188827 1.491588  1.5021527]
(array([6, 7, 9]),) [3.2103436 2.4471738 1.9699732]
(array([ 7,  9, 21]),) [3.1842887 2.7713506 2.4042156]
(array([ 7, 11, 21]),) [5.629892  0.5168801 1.1956438]
(array([16, 21, 22]),) [1.4333332 1.5803924 1.817363 ]
(array([4, 7, 9]),) [2.196287  2.7848973 2.9410996]
(array([ 4,  7, 12]),) [1.7438669 1.5671726 1.6077892]
(array([ 4,  7, 10]),) [1.5142438 1.8789105 2.2368793]
(array([ 3,  4, 22]),) [1.539022  3.8963172 1.4737368]
(array([15, 21, 22]),) [1.7419311 1.2911546 3.0658224]
(array([ 1, 22, 24]),) [0.7810747 1.5545404 1.632463 ]
(array([3, 6, 9]),) [1.433068  1.9165744 2.4081683]
(array([ 6, 12, 16]),) [1.8521487 1.2466706 3.0302284]
(array([16, 20, 22]),) [0.14916807 0.12109764 0.36506122]
(array([13, 22, 24]),) [0.8118085 2.366033  0.9909938]
(array([ 0,  1, 22]),) [1.6441247 0.609713  1.3313658]
(array([15, 19, 22]),) [1.6611779 1.7033662 3.2669692]


In [5]:
l1_weights[0]

array([ 1.2068092 , -0.4023323 , -0.30623418,  1.2395992 , -1.2325739 ,
       -0.45905897,  1.1957302 ,  0.9827033 ,  0.39895543, -2.1509452 ,
        2.1489027 ,  0.33322468, -0.22327988, -0.10303939,  0.38767004,
       -2.9313495 , -1.5027959 ,  0.5955002 ,  1.867734  , -0.24410976,
       -0.6290795 ,  0.7440059 , -1.899377  ,  0.00787763, -1.6625001 ,
        0.5163957 ,  0.05064723], dtype=float32)

In [6]:
len(weights)

2

In [7]:
len(weights[0][0])

27

In [8]:
len(l1_weights.T)

27